apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:v2.11.3
        ports:
        - containerPort: 5000
        command: ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "./artifacts"]
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: mlops
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 31500
